### ISSUE TITLE
WPS not providing error for terria when there is no data for selected area and date range

### ISSUE THREAD

**Issue by pindge** [opendatacube/datacube-wps#7]
**What I did:**

1.  http://terria-cube.terria.io/ 
2.  add data > DEA Development > Fractional Cover > Fractional Cover Daily Observations >Fractional Cover Polygon Drill
3. Click to draw polygon and draw a shape
4. Put start date and end date within the last 10 days
5. this will result in the following due to no data.

When there is no data, the response displayed on terria is 
![image](https://user-images.githubusercontent.com/24644475/73621420-1e89cd00-468a-11ea-95e6-e10dcf0b9764.png)

backend error is

```
{'geopolygon': Geometry(POLYGON ((124.308514670315 -17.4414977385648,124.286942385326 -17.4943556158198,124.398224202236 -17.5051972884613,124.406805061783 -17.4441808911596,124.308514670315 -17.4414977385648)), urn:ogc:def:crs:OGC:1.3:CRS84), 'time': ('2019-12-05', '2020-01-09')}
data load done ls7_fc_albers <xarray.Dataset>
Dimensions:  ()
Data variables:
    *empty*
{'geopolygon': Geometry(POLYGON ((124.308514670315 -17.4414977385648,124.286942385326 -17.4943556158198,124.398224202236 -17.5051972884613,124.406805061783 -17.4441808911596,124.308514670315 -17.4414977385648)), urn:ogc:def:crs:OGC:1.3:CRS84), 'time': ('2019-12-05', '2020-01-09')}
data load done ls5_fc_albers <xarray.Dataset>
Dimensions:  ()
Data variables:
    *empty*
{'geopolygon': Geometry(POLYGON ((124.308514670315 -17.4414977385648,124.286942385326 -17.4943556158198,124.398224202236 -17.5051972884613,124.406805061783 -17.4441808911596,124.308514670315 -17.4414977385648)), urn:ogc:def:crs:OGC:1.3:CRS84), 'time': ('2019-12-05', '2020-01-09'), 'output_crs': 'EPSG:3577', 'resolution': (-25, 25), 'fuse_func': <function wofls_fuser at 0x7f7aee9a86a8>}
data load done wofs_albers <xarray.Dataset>
Dimensions:  ()
Data variables:
    *empty*
{'geopolygon': Geometry(POLYGON ((124.308514670315 -17.4414977385648,124.286942385326 -17.4943556158198,124.398224202236 -17.5051972884613,124.406805061783 -17.4441808911596,124.308514670315 -17.4414977385648)), urn:ogc:def:crs:OGC:1.3:CRS84), 'time': ('2019-12-05', '2020-01-09')}
data load done ls8_fc_albers <xarray.Dataset>
Dimensions:  ()
Data variables:
    *empty*
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pywps/app/Process.py", line 236, in _run_process
    self.handler(wps_request, wps_response)  # the user must update the wps_response.
  File "/code/processes/geometrydrill.py", line 248, in _handler
    outputs = self.custom_handler(masked, process_id=self.uuid)
  File "/code/processes/fcdrill.py", line 43, in _processData
    total = data.count(dim=['x', 'y'])
  File "/usr/local/lib/python3.6/dist-packages/xarray/core/common.py", line 62, in wrapped_func
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/xarray/core/dataset.py", line 3167, in reduce
    % missing_dimensions)
ValueError: Dataset does not contain the dimensions: ['y', 'x']
```

**Comment by pindge** [comment]
On the Terria end the error message is hard coded
https://github.com/TerriaJS/terriajs/blob/e5171bc1cecf8bd01b34b69a6916c5f0b3652c0e/lib/Language/en/translation.json
```
     "asyncShortReportFailed": "Web Processing Service invocation failed.  More details are available on the Info panel.",
```

https://github.com/TerriaJS/terriajs/blob/0aac25567268b6856b3597a6112f9c5cf88fdd0c/lib/Models/WebProcessingServiceCatalogFunction.js#L788-L790
```
    asyncResult.shortReport = i18next.t(
      "models.webProcessingService.asyncShortReportFailed"
    );
```
Server returns
```
<wps:ExecuteResponse xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 ../wpsExecute_response.xsd" service="WPS" version="1.0.0" xml:lang="en-US" serviceInstance="https://ows.dev.dea.ga.gov.au/wps/?request=GetCapabilities&amp;service=WPS" statusLocation="https://s3.ap-southeast-2.amazonaws.com/dea-wps-results/2f9b83da-4799-11ea-b9e4-4eafbe25c318.xml">
<wps:Process wps:processVersion="0.2">
<ows:Identifier>FractionalCoverDrill</ows:Identifier>
<ows:Title>Fractional Cover</ows:Title>
<ows:Abstract>Performs Fractional Cover Polygon Drill</ows:Abstract>
</wps:Process>
<wps:Status creationTime="2020-02-04T21:56:25Z">
<wps:ProcessFailed>
<wps:ExceptionReport>
<ows:Exception exceptionCode="NoApplicableCode" locator="None">
<ows:ExceptionText>Process failed, please check server error log</ows:ExceptionText>
</ows:Exception>
</wps:ExceptionReport>
</wps:ProcessFailed>
</wps:Status>
</wps:ExecuteResponse>
```

**Comment by pindge** [comment]
Exception catching added with the following error message
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<wps:ExecuteResponse xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 ../wpsExecute_response.xsd" service="WPS" version="1.0.0" xml:lang="en-US" serviceInstance="https://ows-testing.dev.dea.ga.gov.au/wps/?request=GetCapabilities&amp;service=WPS" statusLocation="https://s3.ap-southeast-2.amazonaws.com/dea-wps-results/a93c8f04-4965-11ea-9bc0-ae8b8cd457bf.xml">
<wps:Process wps:processVersion="0.2">
<ows:Identifier>FractionalCoverDrill</ows:Identifier>
<ows:Title>Fractional Cover</ows:Title>
<ows:Abstract>Performs Fractional Cover Polygon Drill</ows:Abstract>
</wps:Process>
<wps:Status creationTime="2020-02-07T04:52:37Z">
<wps:ProcessFailed>
<wps:ExceptionReport>
<ows:Exception exceptionCode="NoApplicableCode" locator="None">
<ows:ExceptionText>Process error: No data found for the time period</ows:ExceptionText>
</ows:Exception>
</wps:ExceptionReport>
</wps:ProcessFailed>
</wps:Status>
</wps:ExecuteResponse>
```

**Comment by pindge** [comment]
https://pywps.readthedocs.io/en/latest/process.html#example-process
