### ISSUE TITLE
wps error: OverflowError: cannot serialize a bytes object larger than 4 GiB

### ISSUE THREAD

**Issue by pindge** [opendatacube/datacube-wps#9]
### Expected behaviour
WPS to successfully execute query

### Actual behaviour

```
[2020-02-03 23:10:36 +0000] [10] [INFO] Listening at: http://0.0.0.0:8000 (10)
[2020-02-03 23:10:36 +0000] [10] [INFO] Using worker: sync
[2020-02-03 23:10:36 +0000] [13] [INFO] Booting worker with pid: 13
data load done wofs_albers <xarray.Dataset>
Dimensions:  (time: 340, x: 4511, y: 2222)
Coordinates:
  * time     (time) datetime64[ns] 2015-01-02T00:43:09 ... 2018-12-29T00:32:15.500000
  * y        (y) float64 -2.675e+06 -2.675e+06 ... -2.731e+06 -2.731e+06
  * x        (x) float64 7.033e+05 7.033e+05 7.033e+05 ... 8.16e+05 8.16e+05
Data variables:
    water    (time, y, x) int16 64 64 64 64 64 64 64 64 64 ... 0 0 0 0 0 0 0 0 0
Attributes:
    crs:      EPSG:3577
Process Process-1:4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 181, in _process_worker
    result=r))
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 341, in put
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
OverflowError: cannot serialize a bytes object larger than 4 GiB
```
```
Coordinates:
  * time     (time) datetime64[ns] 2015-01-03T00:35:27.500000 ... 2018-12-29T00:32:15.500000
  * y        (y) float64 -2.675e+06 -2.675e+06 ... -2.731e+06 -2.731e+06
  * x        (x) float64 7.033e+05 7.033e+05 7.033e+05 ... 8.16e+05 8.16e+05
Data variables:
    BS       (time, y, x) int16 -1 -1 -1 -1 -1 -1 -1 -1 ... 84 88 90 84 82 83 82
    PV       (time, y, x) int16 -1 -1 -1 -1 -1 -1 -1 -1 -1 ... 5 7 8 7 7 8 4 4 4
    NPV      (time, y, x) int16 -1 -1 -1 -1 -1 -1 -1 -1 ... 7 7 4 1 7 12 12 12
    UE       (time, y, x) int16 -1 -1 -1 -1 -1 -1 -1 -1 -1 ... 4 5 5 5 4 5 5 5 5
Attributes:
    crs:      EPSG:3577
Process Process-1:2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 181, in _process_worker
    result=r))
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
```
```
Data variables:
    BS       (time, y, x) int16 0 0 0 0 0 0 0 0 0 ... -1 -1 -1 -1 -1 -1 -1 -1 -1
    PV       (time, y, x) int16 49 49 49 48 47 47 47 48 ... -1 -1 -1 -1 -1 -1 -1
    NPV      (time, y, x) int16 52 52 52 53 54 54 54 54 ... -1 -1 -1 -1 -1 -1 -1
    UE       (time, y, x) int16 4 4 4 4 4 4 4 4 4 ... -1 -1 -1 -1 -1 -1 -1 -1 -1
Attributes:
    crs:      EPSG:3577
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pywps/app/Process.py", line 236, in _run_process
    self.handler(wps_request, wps_response)  # the user must update the wps_response.
  File "/code/processes/geometrydrill.py", line 228, in _handler
    d = v.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```
### Steps to reproduce the behaviour

1. http://terria-cube.terria.io/
2. add data > DEA Development > Fractional Cover > Fractional Cover Daily Observations >Fractional Cover Polygon Drill
3. Click to draw polygon and draw a large shape
4. Put start date and end date over 5 years span

**Comment by uchchwhash** [comment]
So we definitely need some guard-rail against users requesting a massive amount of work to be done, and it seems like because of serialization limitations of multiprocessing it may not be feasible to handle >4GB of data at a time.

I think it is a good idea to try to assess the amount of data to be loaded before `load` is called.
